### ISSUE TITLE
Adding Document Feature

### ISSUE THREAD

**Issue by Indhumathi01** [Vigneshwari01/Whatsapp-Development01#3]
Dear Vigneshwari

Please add Document feature which will be helpful in sharing the attachments.

**Comment by Vigneshwari01** [comment]
Hi Indhumathi
Thanks for suggesting this feature. I am working on it and will let you know.

**Comment by Vigneshwari01** [comment]
Dear Indhumathi
Thanks for your suggestion. This feature is going to make our product great.
